---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-cache-tetris-operator-secomind-com-v1alpha1-tetris
  failurePolicy: Fail
  name: mtetris.kb.io
  rules:
  - apiGroups:
    - cache.tetris-operator.secomind.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tetris
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-cache-tetris-operator-secomind-com-v1alpha1-tetris
  failurePolicy: Fail
  name: vtetris.kb.io
  rules:
  - apiGroups:
    - cache.tetris-operator.secomind.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tetris
  sideEffects: None
