# permissions for end users to view tetris.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: tetris-operator
    app.kubernetes.io/managed-by: kustomize
  name: tetris-viewer-role
rules:
- apiGroups:
  - cache.tetris-operator.secomind.com
  resources:
  - tetris
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.tetris-operator.secomind.com
  resources:
  - tetris/status
  verbs:
  - get
