apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: tetris-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Tetris is the Schema for the tetris API
      displayName: Tetris
      kind: Tetris
      name: tetris.cache.tetris-operator.secomind.com
      version: v1alpha2
    - description: Tetris is the Schema for the tetris API
      displayName: Tetris
      kind: Tetris
      name: tetris.cache.tetris-operator.secomind.com
      version: v1alpha1
  description: test
  displayName: tetris-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - test
  links:
  - name: Tetris Operator
    url: https://tetris-operator.domain
  maturity: alpha
  provider:
    name: test
    url: test
  version: 0.0.0
