apiVersion: cache.tetris-operator.secomind.com/v1alpha1
kind: Tetris
metadata:
  labels:
    app.kubernetes.io/name: tetris-operator
    app.kubernetes.io/managed-by: kustomize
  name: tetris-sample
spec:
  replicas: 3
  enableNodePort: false